
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nodeapp-pvc
  labels:
    app: blockchain
spec:
  storageClassName: shared-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 4
  selector:
    matchLabels:
      name: nodeapp
  template:
    metadata:
      labels:
        name: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: mahi30795/demoapp
        command: ["sh", "-c", "sleep 5 && while [ ! -f /shared/artifacts/status_configtxgen_complete ]; do echo Waiting for configtxgen; sleep 1; done; npm start"]
        env:
        - name: PORT
          value: "4000"
        - name: apikey
          value: "thisismyapikey"
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: nodeapp-pvc

---
apiVersion: v1
kind: Service
metadata:
    name: nodeapp
    labels:
      run: nodeapp
spec:
    type: LoadBalancer
    selector:
      name: nodeapp
    ports:
    - protocol: TCP
      nodePort: 30080
      targetPort: 4000
      port: 30080
        
---